name: EMIx
channels:
  - conda-forge
dependencies:
  - fenics-dolfin
  - python=3.10
  - matplotlib
  - git
  - numpy
  - mpich
  - scipy
  - pytest
  - conda-ecosystem-user-package-isolation
  - pyyaml
  - pip:
      - "git+https://github.com/multiphenics/multiphenics.git"
