# Numerical parameters 
time_steps : 100
dt : 0.00005
fem_order: 1
mesh_conversion_factor : 1.0e-6

C_M : 0.02 # membrane capacitance
sigma_i : 1
sigma_e : 1

cell_tag_file         : "../../../data/square/square_regions32.xdmf"
facet_tag_file        : "../../../data/square/square_facets32.xdmf"
intra_restriction_dir : "../../../data/square/square_in_restriction32.rtc.xdmf"
extra_restriction_dir : "../../../data/square/square_ex_restriction32.rtc.xdmf"

ecs_tags : 1
ics_tags : 2
membrane_tags: 2

phi_M_init : -0.06774 #Expression('0.5*sin(10*(x[0]*x[0] + x[1]*x[1]))', degree=4)          

