name: Test KNP-EMI CG code via docker
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: ["main"]
  push:
    branches: ["**"]

env:
  DEB_PYTHON_INSTALL_LAYOUT: deb_system

defaults:
  run:
    shell: bash -el {0}

jobs:
  test_scripts:
    runs-on: ubuntu-latest
    container: ghcr.io/scientificcomputing/fenics:2024-02-19

    steps:
      - uses: actions/checkout@v4

      - name: install package
        run: |
          python3 -m pip install .
      
      - name: Run demos (serial)
        run: 
          python3 -m pytest -m serial -v ./src/tests/test.py
      
      - name: Run demos (MPI (np=2))
        run: 
          python3 -m pytest -m mpi --num-proc=2 -v ./src/tests/test.py
